name: jd_ns

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 * * * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        if: env.JD_COOKIE
        run: |
          npm install
      - name: '运行 【炸年兽】'
        if: env.JD_COOKIE
        run: |
          node jd_ns.js
     
